export const FETCH_DATA_REQUESTED = 'FETCH_DATA_REQUESTED'
export const GET_ALL_REVIEWS_SUCCEED = 'GET_ALL_REVIEWS_SUCCEED';
export const ADD_REVIEW_SUCCEED = 'ADD_REVIEW_SUCCEED';
export const REMOVE_REVIEW_SUCCEED = 'REMOVE_REVIEW_SUCCEED';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';